### ISSUE TITLE
Error pages

### ISSUE THREAD

**Issue by bonswouar** [toaotc/ToaFrameworkExtraBundle#1]
Hi, first thanks for this Bundle it is a good workaround (for https://github.com/symfony/symfony/issues/6857).

Though, I noticed a little problem in my case : on the error pages (404 / 500), the request doesn't have any attribute set (as it's not a "normal" routing). Though on those pages I'd need it to generate some URLs, which would need my required parameter (in my case, it's the domain).

At this moment I get some errors :

> An exception has been thrown during the rendering of a template ("Some mandatory parameters are missing ("domain") to generate a URL for route

Any idea how to get round this issue ?

**Comment by bonswouar** [comment]
_Note: As a workaround I added a default `domain` in those routes, but it's not a real solution as it would generate routes for the wrong  `domain`.._

**Comment by toaotc** [comment]
The attributes come from the router context. In case of an 404 error, there is no route to extract the attributes.
A possible solution could be `{{ path('my_route_name', {'domain' : app.request.host}) }}`.

Hope this helps.

**Comment by bonswouar** [comment]
@toaotc thanks for the quick answer.
I so much didn't want to specify the `domain` myself that I forgot about this obvious workaround, thank you !
